services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webldm-backend
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./example_data:/app/example_data:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webldm-frontend
    restart: unless-stopped
    depends_on:
      - backend
